//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Certificate
    {
        [Editable(false)]
        public int CertificateId { get; set; }
        public string StringId { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public int Downloads { get; set; }
        public byte[] File { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public System.DateTime Expiration { get; set; }
        public byte[] Password { get; set; }
    }
}
