//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using cyber_server.implements.attributes;
    using cyber_server.models;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Plugin : BaseObjectSwModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plugin()
        {
            this.PluginVersions = new HashSet<PluginVersion>();
            this.Tags = new HashSet<Tag>();
            this.Votes = new HashSet<Vote>();
        }

        [Cloneable(false, -1)]
        [Editable(false)]
        public int PluginId { get; set; } = -1;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Cloneable(true
            , cloneOption: CloneOption.Collection
            , collectionType: typeof(PluginVersion))]
        public virtual ICollection<PluginVersion> PluginVersions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Cloneable(true
            , cloneOption: CloneOption.Collection
            , collectionType: typeof(Tag))]
        public virtual ICollection<Tag> Tags { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Cloneable(true
            , cloneOption: CloneOption.Collection
            , collectionType: typeof(Vote))]
        public virtual ICollection<Vote> Votes { get; set; }

        protected override object GenerateNewCloneObjectInstance()
        {
            return new Plugin();
        }
    }
}
