//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluginVersion
    {
        public PluginVersion()
        {

        }

        public int VersionId { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public int PluginId { get; set; }
        public System.DateTime DatePublished { get; set; }
        public string ExecutePath { get; set; }
        public string MainClassName { get; set; }
        public string FolderPath { get; set; }
        public string FileName { get; set; }
        public long CompressLength { get; set; }
        public long RawLength { get; set; }
    
        public virtual Plugin Plugin { get; set; }
    }
}
