//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using cyber_server.implements.attributes;
    using cyber_server.models;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PluginVersion : BaseObjectVersionModel
    {
        public PluginVersion()
        {

        }

        [Cloneable(false, -1)]
        public int PluginId { get; set; }

        [Cloneable(true)]
        public string MainClassName { get; set; }

        [Cloneable(false, null)]
        [JsonIgnore]
        public virtual Plugin Plugin { get; set; }

        public void SetMainClassName(string mainClassName)
        {
            MainClassName = mainClassName;
        }

        protected override object GenerateNewCloneObjectInstance()
        {
            return new PluginVersion();
        }
    }
}
