//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using cyber_server.implements.attributes;
    using cyber_server.models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tool : BaseObjectSwModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tool()
        {
            this.ToolVersions = new HashSet<ToolVersion>();
        }

        [Cloneable(false, -1)]
        [Editable(false)]
        public int ToolId { get; set; } = -1;

        [Cloneable(true)]
        public bool IsShowOnCyberInstaller { get; set; } = true;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Cloneable(true
            , cloneOption: CloneOption.Collection
            , collectionType: typeof(ToolVersion))]
        public virtual ICollection<ToolVersion> ToolVersions { get; set; }

        protected override object GenerateNewCloneObjectInstance()
        {
            return new Tool();
        }
    }
}
