//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using cyber_server.implements.attributes;
    using cyber_server.models;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ToolVersion : BaseObjectVersionModel
    {
        public ToolVersion()
        {

        }

        [Cloneable(false, -1)]
        public int ToolId { get; set; }

        [Cloneable(false, null)]
        [JsonIgnore]
        public virtual Tool Tool { get; set; }

        protected override object GenerateNewCloneObjectInstance()
        {
            return new ToolVersion();
        }
    }
}
