//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using cyber_server.models;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ToolVersion : BaseObjectVersionModel
    {
        public ToolVersion()
        {

        }

        public int ToolId { get; set; }

        public override object Clone()
        {
            byte[] newFile = new byte[File.Length];
            Array.Copy(this.File, newFile, File.Length);
            return new ToolVersion()
            {
                ToolId = -1,
                Version = Version,
                RawLength = RawLength,
                CompressLength = CompressLength,
                DatePublished = DatePublished,
                AssemblyName = AssemblyName,
                Description = Description,
                ExecutePath = ExecutePath,
                FileName = FileName,
                File = newFile,
                VersionId = -1,
                Tool = null,
            };
        }

        [JsonIgnore]
        public virtual Tool Tool { get; set; }
    }
}
