//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_server
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vote
    {
        public int Stars { get; set; }

        [Editable(false)]
        public int VoteId { get; set; }
        public int PluginId { get; set; }
    
        [JsonIgnore]
        public virtual Plugin Plugin { get; set; }
    }
}
